# Generated by Django 4.2.26 on 2025-11-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "العربية")],
                default="en",
                help_text="Preferred language",
                max_length=10,
            ),
        ),
    ]
