# Generated by Django 4.2.26 on 2025-11-13 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_problem",
                    models.TextField(
                        help_text="Description of the potential risk/expected problem"
                    ),
                ),
                (
                    "impact",
                    models.TextField(help_text="Expected impact if this risk occurs"),
                ),
                (
                    "estimated_resolution_duration",
                    models.PositiveIntegerField(
                        help_text="Estimated time to resolve this risk"
                    ),
                ),
                (
                    "resolution_duration_unit",
                    models.CharField(
                        choices=[
                            ("HOURS", "Hours"),
                            ("DAYS", "Days"),
                            ("WEEKS", "Weeks"),
                        ],
                        default="HOURS",
                        help_text="Unit for resolution duration",
                        max_length=10,
                    ),
                ),
                (
                    "mitigation_notes",
                    models.TextField(
                        blank=True,
                        help_text="Action plan and mitigation notes (optional)",
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        help_text="Risk severity level",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        help_text="Current status of this risk",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Locked by BCM Manager after review (prevents department editing)",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True, help_text="When this risk was locked", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this risk was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this risk was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this risk entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this risk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="departments.department",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="BCM Manager who locked this risk",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this risk",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk",
                "verbose_name_plural": "Risks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["department", "status"],
                        name="risks_risk_departm_4b4dbb_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="risks_risk_severit_3a498e_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="risks_risk_created_1d9336_idx"
                    ),
                ],
            },
        ),
    ]
